services:
  - type: worker
    name: community-discord-bot
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm run start:host
    envVars:
      - key: DISCORD_TOKEN
        sync: false
      - key: CLIENT_ID
        sync: false
      - key: GUILD_ID
        sync: false
      - key: OWNER_ID
        sync: false
      - key: NODE_VERSION
        value: "20"
